# This is a basic workflow to help you get started with Actions

name: Auto List Readme

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # setup
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: rewriteReadme
        uses: seed-of-apricot/issue-list-readme@v1.1.0
        with:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          pattern: '<!-- issueTable -->' # suffixing "Demo" for this readme
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
